baseURL = "https://blog.bakarimustafa.com/"
languageCode = "en-us"
title = "Bakari Mustafa"
theme = "ink"
paginate = 6

copyright = "© 2020 Bakari Mustafa"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-69813719-2"
disqusShortname = "bakari"

[params]
	subtitle = "Thoughts and Ideas."

	# Optional 64x64 avatar image.
	avatar = ""

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true
	
	# The path must be relative to the static folder
	# favicon = "favicon.ico"

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.
	
 [params.favicon]
  # relURL is applied to path 
  enable    = true
  path      = "/img"
  themeColor= "#000" 
  
# Navigation Menu
#[[menu.main]]
#name = "Home"
#url = "/"
#weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Education"
url = "/education"
weight = 3

[[menu.main]]
name = "Books"
url = "/books"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 6

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/realbakari"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/realbakari"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/realbakari"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
   categories = "categories"
   education = "education"
   books = "books"
