baseURL = "https://blog.bakarimustafa.com/"
languageCode = "en-us"
title = "Bakari Mustafa"
theme = "ink"
paginate = 6

copyright = "2020 © Bakari Mustafa"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-69813719-2"
disqusShortname = "bakari"

[params]
	subtitle = "Thougts, Ideas and Insights."

	# Optional 64x64 avatar image.
	avatar = ""

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/realbakari"


[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/realbakari"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"
